workflows:
  android-live-build:
    name: Urban Auto - Clean Stable Build
    max_build_duration: 120

    environment:
      node: 20
      java: 21

    scripts:

      - name: Hard Clean
        script: |
          rm -rf node_modules
          rm -rf package-lock.json
          rm -rf android
          npm cache clean --force

      - name: Install Dependencies (peer safe)
        script: |
          npm install --legacy-peer-deps

      - name: Build Next.js
        script: |
          npm run build

      - name: Add Android Platform Fresh
        script: |
          npx cap add android
          npx cap sync android

      - name: Fix Gradle Wrapper (force 8.13)
        script: |
          cd android
          rm -rf gradle/wrapper
          gradle wrapper --gradle-version 8.13
          chmod +x gradlew
          cd ..

      - name: Build Release APK + AAB
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
